import {useCallback,useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowLeft,Bot,Calendar,Settings,Send,RefreshCw,Users,MessageSquare} from 'lucide-react';
import apiClient from '@/lib/apiClient';
import ActionConfirmation from '@/components/maria/ActionConfirmation';
const statusLabels={confirme:'Confirmé',en_attente:'En attente',annule:'Annulé',termine:'Terminé',no_show:'Absent'};
export default function ReceptionnistIA(){
 const navigate=useNavigate(),[data,setData]=useState(null),[tab,setTab]=useState('assistant'),[error,setError]=useState(''),[messages,setMessages]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null),[notice,setNotice]=useState('');const end=useRef(null);
 const refresh=useCallback(async()=>{try{const r=await apiClient.get('/pro/receptionist');setData(r);setForm(prev=>prev||r.settings);setError('');}catch(e){setError(e.message);}},[]);
 useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages]);
 async function send(text){
  const content=(text||input).trim();if(!content||busy)return;
  setInput('');setBusy(true);setError('');const next=[...messages,{role:'user',content}];setMessages(next);
  try{const r=await apiClient.post('/ai/maria',{mode:'receptionist',messages:next.slice(-20).map(({role,content})=>({role,content}))});setMessages(prev=>[...prev,{role:'assistant',content:r.choices[0].message.content,actions:r.actions}]);}catch(e){setError(e.message);}finally{setBusy(false);}
 }
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await apiClient.put('/pro/receptionist',form);setForm(r.settings);await refresh();setNotice('Les paramètres sont enregistrés pour votre activité.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function update(kind,id,status){setBusy(true);setError('');try{await apiClient.put('/pro/'+kind+'/'+id,{status});await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const pending=data?.bookings.filter(r=>r.status==='en_attente').length||0;
 return <main className="min-h-full bg-[#f3f6f2] text-[#173e32] pb-28"><header className="p-5 bg-white border-b flex items-center gap-3"><button aria-label="Retour à Scaling Business" onClick={()=>navigate(-1)} className="p-3 bg-gray-100 rounded-xl"><ArrowLeft size={20}/></button><div className="flex-1"><p className="text-xs uppercase tracking-widest text-gray-500">Maria · Scaling Business</p><h1 className="text-xl font-bold">Réceptionniste IA</h1><p className="text-sm text-gray-500">{data?.professional.salon_name}</p></div><button aria-label="Actualiser la réceptionniste" className="p-3" onClick={refresh}><RefreshCw size={20}/></button></header>
  <div className="max-w-5xl mx-auto p-5 space-y-5">
   {error&&<p role="alert" className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-800">{error}</p>}{notice&&<p role="status" className="p-4 bg-emerald-50 rounded-xl">{notice}</p>}
   {!data&&!error&&<p role="status">Chargement de votre activité…</p>}
   {data&&<>
    <div className="grid grid-cols-3 gap-3">{[['Dans les 7 jours',data.bookings.length],['À confirmer',pending],['Demandes à traiter',data.leads.filter(l=>l.status==='new').length+data.handoffs.filter(h=>h.status==='pending').length]].map(([label,n])=><div key={label} className="bg-white p-4 rounded-2xl"><p className="text-xs text-gray-500">{label}</p><strong className="text-3xl block mt-2">{n}</strong></div>)}</div>
    <nav className="flex gap-2 overflow-x-auto" aria-label="Sections de la réceptionniste">{[['assistant','Assistante',Bot],['agenda','Agenda',Calendar],['requests','Demandes',Users],['settings','Paramètres',Settings]].map(([value,label,Icon])=><button key={value} onClick={()=>setTab(value)} aria-current={tab===value?'page':undefined} className={'flex gap-2 items-center whitespace-nowrap min-h-12 rounded-xl px-4 py-3 '+(tab===value?'bg-[#214f3e] text-white':'bg-white')}><Icon size={18}/>{label}</button>)}</nav>
    {tab==='assistant'&&<section className="bg-white rounded-2xl p-5 space-y-4">
     {!data.settings.enabled&&<div className="p-4 rounded-xl bg-amber-50 text-amber-900">Votre assistante est désactivée.<button className="underline ml-2 p-2" onClick={()=>setTab('settings')}>Ouvrir les paramètres</button></div>}
     {messages.length===0&&<><Bot size={32}/><h2 className="text-xl font-bold">Un accueil organisé, un agenda à jour.</h2><p className="text-gray-500">Consultez vos rendez-vous et vos demandes clients. Les changements proposés attendent votre confirmation.</p><div className="flex flex-wrap gap-2">{['Quels rendez-vous attendent ma confirmation ?','Quelles demandes clients dois-je traiter ?','Aide-moi à organiser mon agenda cette semaine.'].map(text=><button className="p-3 rounded-xl border text-left" disabled={busy} key={text} onClick={()=>send(text)}>{text}</button>)}</div></>}
     <div className="space-y-4">{messages.map((m,i)=><article key={i} className={'p-4 rounded-xl '+(m.role==='user'?'bg-gray-50 ml-6':'bg-emerald-50 mr-3')}><p className="text-xs font-bold mb-2">{m.role==='user'?'Vous':'Réceptionniste IA'}</p><p className="whitespace-pre-wrap text-sm leading-relaxed">{m.content}</p>{m.actions?.map(p=><ActionConfirmation key={p.id} proposal={p} onConfirmed={refresh}/>)}</article>)}{busy&&<p role="status">Traitement en cours…</p>}<div ref={end}/></div>
     <form className="flex gap-2 border-t pt-4" onSubmit={e=>{e.preventDefault();send();}}><label className="flex-1"><span className="sr-only">Votre demande à la réceptionniste</span><input value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} className="w-full border rounded-xl p-3" placeholder="Une question sur votre activité…"/></label><button className="p-3 bg-[#214f3e] text-white rounded-xl disabled:opacity-40" aria-label="Envoyer la demande" disabled={busy||!input.trim()}><Send size={20}/></button></form>
    </section>}
    {tab==='agenda'&&<section className="bg-white rounded-2xl p-5 space-y-3"><h2 className="font-bold text-xl">Les sept prochains jours</h2><p className="text-sm text-gray-500">Heures du salon · {data.professional.timezone}</p>{data.bookings.length===0?<p>Aucun rendez-vous sur cette période.</p>:data.bookings.map(r=><article className="p-4 border rounded-xl flex justify-between flex-wrap gap-3" key={r.id}><div><h3 className="font-bold">{r.service_name}</h3><p className="text-sm text-gray-500">{r.client_name} · {String(r.date).slice(0,10)} à {r.time_slot}</p></div><span className="text-sm">{statusLabels[r.status]||r.status}</span>{['en_attente','confirme'].includes(r.status)&&<button className="underline text-sm p-2" onClick={()=>{setTab('assistant');send('Propose de '+(r.status==='en_attente'?'confirmer':'annuler')+' le rendez-vous '+r.id);}}>Préparer une modification</button>}</article>)}</section>}
    {tab==='requests'&&<section className="bg-white rounded-2xl p-5 space-y-4"><h2 className="font-bold text-xl flex gap-2"><MessageSquare/>Les demandes de vos clients</h2>{data.leads.length+data.handoffs.length===0&&<p>Aucune demande reçue.</p>}{[...data.leads.map(l=>({...l,kind:'leads'})),...data.handoffs.map(l=>({...l,kind:'handoffs'}))].map(r=><article key={r.id} className="border rounded-xl p-4 space-y-2"><h3 className="font-bold">{r.customer_name||'Client BeautyBook'}</h3>{r.customer_email&&<p className="text-sm">{r.customer_email}</p>}<p className="text-sm whitespace-pre-wrap">{r.need||r.reason}</p><label className="text-sm block">Avancement<select disabled={busy} className="border rounded-xl p-3 block mt-1" value={r.status} onChange={e=>update(r.kind,r.id,e.target.value)}>{(r.kind==='leads'?[['new','Nouvelle'],['contacted','Contacté'],['converted','Converti'],['closed','Clôturé']]:[['pending','En attente'],['accepted','Prise en charge'],['resolved','Résolue']]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></article>)}</section>}
    {tab==='settings'&&form&&<section className="bg-white rounded-2xl p-5"><h2 className="font-bold text-xl mb-4">Votre accueil</h2><form onSubmit={save} className="space-y-5"><label className="flex gap-3 items-center min-h-12"><input type="checkbox" className="w-5 h-5" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/>Activer l’assistante de gestion</label><label className="block text-sm font-bold">Message d’accueil<textarea className="block w-full border rounded-xl p-3 mt-2 font-normal" required minLength={5} maxLength={240} value={form.welcome_text} onChange={e=>setForm(f=>({...f,welcome_text:e.target.value}))}/></label><label className="block text-sm font-bold">Consignes pour votre accueil<textarea className="block w-full border rounded-xl p-3 mt-2 font-normal" rows={5} maxLength={2000} value={form.business_instructions} onChange={e=>setForm(f=>({...f,business_instructions:e.target.value}))} placeholder="Votre ton, les informations pratiques utiles aux clients…"/></label><p className="text-sm text-gray-500">Les prestations, prix et disponibilités sont toujours lus dans votre activité. Les consignes ne modifient pas les droits d’accès.</p><button disabled={busy} className="p-3 bg-[#214f3e] text-white rounded-xl">{busy?'Enregistrement…':'Enregistrer les paramètres'}</button></form></section>}
   </>}
  </div>
 </main>;
}
