import { useEffect, useRef, useState, useCallback } from 'react';
import { Store, LayoutDashboard, Package, ShoppingBag, Boxes, Settings, ArrowUpRight, ArrowRight, Plus, Search, RefreshCw, LogOut, X, Upload, AlertCircle, Check, ChevronRight, Truck, Camera, ArrowDownToLine } from 'lucide-react';
import { configured, supabase, api, uploadProductImage } from './api';
import SellerCommerce from './SellerCommerce';
import SellerAuth, { SellerPasswordReset } from './SellerAuth';

const money=value=>Number(value||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const dates=value=>new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'short'});
const statusLabel={actif:'En ligne',inactif:'En pause',brouillon:'Brouillon',pending:'En attente de paiement',paid:'À préparer',preparing:'En préparation',shipped:'Expédiée',delivered:'Livrée',cancelled:'Annulée',refunded:'Remboursée'};
const navigation=[['overview','Vue d’ensemble',LayoutDashboard],['products','Catalogue',Package],['orders','Commandes',ShoppingBag],['inventory','Stock',Boxes],['settings','Ma boutique',Store]];

function Brand(){return <div className="brand"><span className="brand-icon"><Store size={23}/></span><span>BeautyBook<small>ESPACE VENDEUR</small></span></div>;}
function Notice({children}){return <div className="notice" role="alert"><AlertCircle size={20}/><span>{children}</span></div>;}
function Empty({icon:Icon=Package,title,children,action}){return <div className="empty"><Icon size={36}/><h3>{title}</h3><p>{children}</p>{action}</div>;}


function ProductDialog({product,onClose,onSaved}){
 const ref=useRef(null),fileRef=useRef(null);
 const [form,setForm]=useState({name:product?.name||'',description:product?.description||'',price:product?.price??'',old_price:product?.old_price??'',category:product?.category||'',brand:product?.brand||'',images:product?.images||[],status:product?.status||'brouillon',min_qty:product?.min_qty||1});
 const [saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);
 const update=(key,value)=>setForm(old=>({...old,[key]:value}));
 async function upload(event){const file=event.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const url=await uploadProductImage(file);setForm(old=>({...old,images:[...old.images,url].slice(0,8)}));}catch(err){setError(err.message);}finally{setUploading(false);}}
 async function submit(event){event.preventDefault();setSaving(true);setError('');try{await api('/products'+(product?.id?'/'+product.id:''),{method:product?.id?'PUT':'POST',body:{...form,price:Number(form.price),min_qty:Number(form.min_qty)}});await onSaved();onClose();}catch(err){setError(err.message);}finally{setSaving(false);}}
 return <dialog ref={ref} onCancel={onClose} aria-labelledby="product-title"><div className="dialog-head"><div><p className="eyebrow">VOTRE CATALOGUE</p><h2 id="product-title">{product?.id?'Modifier le produit':'Ajouter un produit'}</h2></div><button className="icon-button" aria-label="Fermer" onClick={onClose}><X/></button></div>
 <form onSubmit={submit} className="dialog-body"><div className="product-photos">{form.images.map((url,index)=><div key={url}><SellerImage src={url} alt={'Photo produit '+(index+1)} /><button type="button" aria-label="Retirer cette photo" onClick={()=>update('images',form.images.filter((_,i)=>i!==index))}><X size={16}/></button></div>)}{form.images.length<8&&<button type="button" className="photo-add" onClick={()=>fileRef.current.click()} disabled={uploading}><Camera size={25}/>{uploading?'Envoi…':'Ajouter une photo'}</button>}<input hidden ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></div>
 <label>Nom du produit<input required maxLength={180} value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Description<textarea rows={3} maxLength={5000} value={form.description} onChange={e=>update('description',e.target.value)}/></label>
 <div className="form-grid"><label>Prix (€)<input type="number" required min="0.01" step="0.01" value={form.price} onChange={e=>update('price',e.target.value)}/></label><label>Ancien prix (€)<input type="number" min="0" step="0.01" value={form.old_price} onChange={e=>update('old_price',e.target.value)}/></label><label>Catégorie<input value={form.category} onChange={e=>update('category',e.target.value)}/></label><label>Marque<input value={form.brand} onChange={e=>update('brand',e.target.value)}/></label><label>Quantité minimum<input type="number" min="1" required value={form.min_qty} onChange={e=>update('min_qty',e.target.value)}/></label><label>Publication<select value={form.status} onChange={e=>update('status',e.target.value)}><option value="brouillon">Brouillon</option><option value="actif">En ligne</option><option value="inactif">En pause</option></select></label></div>
 <p className="muted">Les quantités se gèrent dans Stock pour conserver l’historique de chaque mouvement.</p>{error&&<Notice>{error}</Notice>}<footer className="dialog-actions"><button type="button" className="button" onClick={onClose}>Annuler</button><button className="button primary" disabled={saving||uploading}>{saving?'Enregistrement…':'Enregistrer le produit'}</button></footer></form></dialog>;
}

function StockDialog({product,onClose,onSaved}){
 const ref=useRef(null),request=useRef(crypto.randomUUID());const [quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{ref.current.showModal();},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api(`/products/${product.id}/stock`,{method:'POST',body:{quantity:Number(quantity),reason},requestKey:request.current});await onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <dialog ref={ref} onCancel={onClose} aria-labelledby="stock-title"><div className="dialog-head"><h2 id="stock-title">Ajuster le stock</h2><button className="icon-button" onClick={onClose} aria-label="Fermer"><X/></button></div><form onSubmit={submit} className="dialog-body"><p><strong>{product.name}</strong><br/><span className="muted">Stock actuel : {product.stock} unité(s)</span></p><label>Quantité à ajouter ou à retirer<input type="number" step="1" required value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Ex. 20 ou -2"/></label><label>Motif<textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Réception fournisseur, inventaire, produit abîmé…"/></label>{error&&<Notice>{error}</Notice>}<button className="button primary full" disabled={busy}>{busy?'Enregistrement…':'Enregistrer le mouvement'}</button></form></dialog>;
}

function ShipmentDialog({children,onClose}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();},[]);return <dialog ref={ref} onCancel={onClose} aria-labelledby="shipment-title">{children}</dialog>;}
function Orders({orders,onSaved}){
 const [filter,setFilter]=useState('all'),[selected,setSelected]=useState(null),[tracking,setTracking]=useState(''),[carrier,setCarrier]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const filtered=orders.filter(order=>filter==='all'||order.status===filter);
 async function update(order,status){setBusy(true);setError('');try{await api('/orders/'+order.id,{method:'PUT',body:{status,...(status==='shipped'?{tracking_number:tracking,carrier}:{})}});setSelected(null);await onSaved();}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <><div className="toolbar"><div className="chips">{[['all','Toutes'],['paid','À préparer'],['preparing','Préparation'],['shipped','Expédiées']].map(([value,label])=><button key={value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{label}</button>)}</div><span className="muted">{filtered.length} ligne(s)</span></div>{error&&<Notice>{error}</Notice>}
 {filtered.length===0?<Empty icon={ShoppingBag} title="Aucune commande dans cette vue">Vos commandes apparaîtront ici dès qu’elles seront enregistrées.</Empty>:<div className="orders-list">{filtered.map(order=><article className="order-card" key={order.id}><div className="order-top"><span className="reference">#{order.order_id.slice(0,8).toUpperCase()}</span><span className={'status '+order.status}>{statusLabel[order.status]||order.status}</span></div><h3>{order.product_name}</h3><p className="muted">{order.quantity} unité(s) · {dates(order.created_at)}</p>{order.shipping_address&&<address className="shipping-address">{order.shipping_address.firstName} {order.shipping_address.lastName}<br/>{order.shipping_address.address1}<br/>{order.shipping_address.address2&&<>{order.shipping_address.address2}<br/></>}{order.shipping_address.zip} {order.shipping_address.city} · {order.shipping_address.country}{order.shipping_address.phone&&<><br/>{order.shipping_address.phone}</>}</address>}<div className="order-bottom"><strong>{money(order.quantity*order.unit_price)}</strong>{order.status==='paid'&&<button className="button small" disabled={busy} onClick={()=>update(order,'preparing')}>Préparer <ArrowRight size={16}/></button>}{order.status==='preparing'&&<button className="button small" onClick={()=>setSelected(order)}>Expédier <Truck size={16}/></button>}{order.status==='shipped'&&<div className="tracking"><span>{order.carrier} · {order.tracking_number}</span><button className="button small" disabled={busy} onClick={()=>update(order,'delivered')}>Confirmer la livraison</button></div>}</div></article>)}</div>}
 {selected&&<ShipmentDialog onClose={()=>setSelected(null)}><div className="dialog-head"><h2 id="shipment-title">Enregistrer l’expédition</h2><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Fermer"><X/></button></div><form className="dialog-body" onSubmit={e=>{e.preventDefault();update(selected,'shipped');}}><label>Transporteur<input required value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Numéro de suivi<input required value={tracking} onChange={e=>setTracking(e.target.value)}/></label>{error&&<Notice>{error}</Notice>}<button className="button primary" disabled={busy}>{busy?'Enregistrement…':'Confirmer l’expédition'}</button></form></ShipmentDialog>}</>;
}

function SettingsView({account,onSaved}){
 const [name,setName]=useState(account.shop_name),[threshold,setThreshold]=useState(account.low_stock_threshold),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{await api('/settings',{method:'PUT',body:{shop_name:name,low_stock_threshold:Number(threshold)}});await onSaved();setMessage('Les paramètres de votre boutique sont enregistrés.');}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <section className="panel settings-panel"><h2>Les essentiels de votre boutique</h2><p className="muted">Ces informations sont partagées par vos espaces web et mobile.</p><form onSubmit={submit}><label>Nom de la boutique<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Seuil d’alerte de stock<input type="number" min="0" required value={threshold} onChange={e=>setThreshold(e.target.value)}/><small>Les produits à ce seuil ou en dessous seront signalés dans votre tableau de bord.</small></label>{error&&<Notice>{error}</Notice>}{message&&<p className="success" role="status"><Check size={18}/>{message}</p>}<button className="button primary" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button></form></section>;
}

function Workspace({session}){
 const [tab,setTab]=useState(new URLSearchParams(location.search).get('section')==='settings'?'settings':'overview'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[query,setQuery]=useState(''),[product,setProduct]=useState(null),[stock,setStock]=useState(null),[shop,setShop]=useState(''),[applying,setApplying]=useState(false),[application,setApplication]=useState(null);
 const refresh=useCallback(async()=>{setLoading(true);try{const result=await api('/overview');setData(result);setError(null);}catch(err){setError(err);}finally{setLoading(false);}},[]);
 useEffect(()=>{refresh();const tick=setInterval(()=>{if(document.visibilityState==='visible')refresh();},60000);return()=>clearInterval(tick);},[refresh]);
 const current=navigation.find(item=>item[0]===tab);
 const products=data?.products.filter(p=>[p.name,p.brand,p.category].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())))||[];
 const low=data?.products.filter(p=>p.status==='actif'&&p.stock<=data.account.low_stock_threshold)||[];
 async function apply(e){e.preventDefault();setApplying(true);try{const result=await api('/apply',{method:'POST',body:{shop_name:shop}});setApplication(result.account.status);await refresh();}catch(err){setError(err);}finally{setApplying(false);}}
 function exportStock(){const escape=v=>'"'+String(v??'').replaceAll('"','""').replace(/^[=+\-@\t\r]/,match=>"'"+match)+'"';const lines=[['Produit','Référence','Stock','Prix'],...data.products.map(p=>[p.name,p.id,p.stock,p.price])];const blob=new Blob(['\uFEFF'+lines.map(row=>row.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='beautybook-stock-'+new Date().toISOString().slice(0,10)+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="workspace"><aside className="sidebar"><Brand/><p className="nav-label">VOTRE ESPACE</p><nav aria-label="Navigation principale">{navigation.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setQuery('');}} aria-current={tab===id?'page':undefined}><Icon size={21}/><span>{label}</span>{id==='orders'&&data?.stats.to_prepare>0&&<b>{data.stats.to_prepare}</b>}</button>)}</nav><div className="sidebar-bottom"><span className="seller-avatar">{(data?.account.shop_name||session.user.email||'B').slice(0,1).toUpperCase()}</span><div><strong>{data?.account.shop_name||'Mon compte'}</strong><small>{session.user.email}</small></div><button className="icon-button" aria-label="Se déconnecter" onClick={()=>supabase.auth.signOut()}><LogOut size={19}/></button></div></aside>
 <div className="content"><header className="topbar"><span className="breadcrumb">Mon espace <ChevronRight size={14}/> {current[1]}</span><div><span className="connection">Espace vendeur</span><button className="icon-button mobile-logout" aria-label="Se déconnecter" onClick={()=>supabase.auth.signOut()}><LogOut size={19}/></button><button className="icon-button" aria-label="Actualiser les données" disabled={loading} onClick={refresh}><RefreshCw size={19} className={loading?'spinning':''}/></button></div></header><main className="main"><div className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</p><h1>{tab==='overview'?'Votre activité, en un regard.':current[1]}</h1><p className="muted">{tab==='overview'?'L’essentiel pour organiser votre journée.':tab==='products'?'Faites vivre votre catalogue et vos nouveautés.':tab==='orders'?'De la préparation à la livraison.':tab==='inventory'?'Un stock juste. Des mouvements tracés.':'Un espace à l’image de votre activité.'}</p></div>{data&&tab==='products'&&<button className="button primary" onClick={()=>setProduct({})}><Plus size={19}/>Ajouter un produit</button>}{data&&tab==='inventory'&&<button className="button" onClick={exportStock}><ArrowDownToLine size={19}/>Exporter le stock</button>}</div>
 {error&&<Notice>{error.message}<button className="text-button" onClick={refresh}>Réessayer</button></Notice>}
 {application&&<p role="status" className="success">{application==='pending'?'Votre demande est enregistrée et attend sa validation.':application==='suspended'?'Votre boutique est suspendue. Contactez le support.':'Votre boutique est active.'}</p>}{error?.code==='SELLER_APPROVAL_REQUIRED'&&!data&&!application&&<section className="panel settings-panel"><h2>Demandez l’ouverture de votre boutique</h2><p className="muted">Si une demande est déjà en cours, elle sera conservée pour validation.</p><form onSubmit={apply}><label>Nom de votre boutique<input required minLength={2} value={shop} onChange={e=>setShop(e.target.value)}/></label><button className="button primary" disabled={applying}>{applying?'Envoi…':'Envoyer ma demande'}</button></form></section>}
 {loading&&!data&&!error&&<div className="loading-state" role="status"><RefreshCw className="spinning"/>Chargement de votre activité…</div>}
 {data&&<>
 {tab==='overview'&&<><div className="metrics"><article className="metric highlight"><span>Ventes enregistrées <ArrowUpRight size={19}/></span><strong>{money(data.stats.sales_total)}</strong><small>Commandes payées, hors remboursements</small></article><article className="metric"><span>À préparer <ShoppingBag size={19}/></span><strong>{data.stats.to_prepare}</strong><small>Lignes de commandes à traiter</small></article><article className="metric"><span>Au catalogue <Package size={19}/></span><strong>{data.stats.product_count}</strong><small>Produits de votre boutique</small></article><article className="metric"><span>Stocks à surveiller <Boxes size={19}/></span><strong>{data.stats.low_stock_count}</strong><small>Selon votre seuil d’alerte</small></article></div>
 <div className="overview-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">À GARDER À L’ŒIL</p><h2>Vos stocks bas</h2></div><button className="text-button" onClick={()=>setTab('inventory')}>Voir le stock <ArrowUpRight size={16}/></button></div>{low.length?low.slice(0,5).map(p=><div className="compact-product" key={p.id}><ProductImage product={p}/><div><strong>{p.name}</strong><small>{p.category||'Produit'}</small></div><span className="stock-warning">{p.stock} restant(s)</span><button className="icon-button" aria-label={'Ajuster le stock de '+p.name} onClick={()=>setStock(p)}><Plus size={20}/></button></div>):<Empty icon={Check} title="Aucun stock bas">Votre seuil d’alerte vous aide à anticiper les réapprovisionnements.</Empty>}</section>
 <section className="panel activity"><div className="section-heading"><div><p className="eyebrow">DERNIERS MOUVEMENTS</p><h2>Le fil de votre boutique</h2></div></div>{data.movements.length?data.movements.slice(0,5).map(m=><div className="activity-item" key={m.id}><span className={m.quantity>0?'movement-icon positive':'movement-icon'}>{m.quantity>0?'+':''}{m.quantity}</span><div><strong>{m.name}</strong><p>{m.reason}</p><small>{dates(m.created_at)} · Stock : {m.stock_after}</small></div></div>):<Empty icon={Boxes} title="Votre activité commence ici">Ajoutez vos produits puis enregistrez votre premier stock.</Empty>}</section></div><section className="next-step"><div><p className="eyebrow">FAITES GRANDIR VOTRE CATALOGUE</p><h2>Votre prochain coup de cœur mérite sa place.</h2><p>Ajoutez vos nouveautés, leurs photos et leurs informations.</p></div><button className="button primary" onClick={()=>setProduct({})}>Ajouter un produit <Plus size={18}/></button></section></>}
 {(tab==='products'||tab==='inventory')&&<><div className="toolbar"><label className="search"><Search size={19}/><input aria-label="Rechercher dans le catalogue" placeholder="Rechercher un produit, une marque…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="muted">{products.length} produit(s)</span></div>{products.length===0?<Empty title={query?'Aucun produit trouvé':'Votre catalogue attend ses premiers produits'}>{query?'Essayez un autre nom ou une autre marque.':'Ajoutez un produit, puis renseignez votre stock pour le proposer à la vente.'}</Empty>:<section className="panel product-table"><div className="table-header"><span>Produit</span><span>Prix</span><span>Stock</span><span>État</span><span>Action</span></div>{products.map(p=><div className="product-row" key={p.id}><div className="product-cell"><ProductImage product={p}/><div><strong>{p.name}</strong><small>{p.brand||p.category||'Sans catégorie'}</small></div></div><span className="product-price">{money(p.price)}</span><span className={p.stock<=data.account.low_stock_threshold?'stock-warning':''}>{p.stock} <small>unité(s)</small></span><span className={'status '+p.status}>{statusLabel[p.status]||p.status}</span><button className="button small" onClick={()=>tab==='inventory'?setStock(p):setProduct(p)}>{tab==='inventory'?'Ajuster':'Modifier'}<ChevronRight size={16}/></button></div>)}</section>}{tab==='inventory'&&data.movements.length>0&&<section className="panel history"><h2>Historique des mouvements</h2>{data.movements.map(m=><div className="history-row" key={m.id}><span>{dates(m.created_at)}</span><strong>{m.name}</strong><span>{m.reason}</span><b>{m.quantity>0?'+':''}{m.quantity}</b><span>Stock : {m.stock_after}</span></div>)}</section>}</>}
 {tab==='orders'&&<Orders orders={data.orders} onSaved={refresh}/>}{tab==='settings'&&<><SettingsView account={data.account} onSaved={refresh}/><SellerCommerce account={data.account} onSaved={refresh}/></>}
 </>}
 </main></div>{product&&<ProductDialog product={product} onClose={()=>setProduct(null)} onSaved={refresh}/>} {stock&&<StockDialog product={stock} onClose={()=>setStock(null)} onSaved={refresh}/>}</div>;
}
function SellerImage({src,alt='',className=''}){const [failedSrc,setFailedSrc]=useState(null);if(!src||failedSrc===src)return <span role="img" className={`seller-image-fallback ${className}`} aria-label={`${alt} — visuel indisponible`}><Package size={22}/></span>;return <img className={className} src={src} alt={alt} loading="lazy" onError={()=>setFailedSrc(src)} />;}
function ProductImage({product}){const src=Array.isArray(product.images)?product.images[0]:null;return <SellerImage src={src} alt={product.name} className="product-image"/>;}

export default function App(){const [session,setSession]=useState(null),[loading,setLoading]=useState(configured),[recovery,setRecovery]=useState(new URLSearchParams(location.search).get('auth')==='recovery'),[error,setError]=useState('');
 useEffect(()=>{
   if(!supabase)return; let alive=true,received=false;
   const hash=new URLSearchParams(location.hash.slice(1));
   if(hash.has('error')||new URLSearchParams(location.search).has('error'))setError('Ce lien a expiré ou a déjà été utilisé. Demandez un nouvel email.');
   const {data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{if(!alive)return;received=true;setSession(next);setLoading(false);if(next?.user?.email_confirmed_at)sessionStorage.removeItem('bb-seller-confirmation');if(event==='PASSWORD_RECOVERY')setRecovery(true);});
   supabase.auth.getSession().then(({data,error})=>{if(!alive)return;if(!received)setSession(data?.session||null);if(error)setError('Impossible de récupérer votre session. Reconnectez-vous.');setLoading(false);}).catch(()=>{if(alive){setError('Connexion impossible. Réessayez.');setLoading(false);}});
   return()=>{alive=false;subscription.unsubscribe();};
 },[]);
 if(loading)return <main className="loading-state" role="status"><RefreshCw className="spinning"/>Ouverture de votre espace…</main>;
 if(recovery&&session)return <SellerPasswordReset onComplete={()=>{setRecovery(false);history.replaceState(null,'',location.pathname);}}/>;
 return session?<Workspace session={session}/>:<SellerAuth sessionError={error}/>;
}
